#!/usr/bin/env node
/**
 * Generate `frontend/lib/api.gen.ts` from the FastAPI app's OpenAPI schema.
 *
 * Why a Node script (not just a `pnpm exec` one-liner): we need to invoke
 * the backend's `app.openapi()` *without* booting uvicorn — running
 * uvicorn in a CI step would race startup against the curl that fetches
 * the JSON. Importing the FastAPI app directly via `python -c …` is
 * deterministic and finishes in well under a second.
 *
 * Usage
 * -----
 *   pnpm gen:api
 *
 * Re-run after any backend router / pydantic schema change. The output
 * file is committed; CI does NOT run codegen because that would require
 * a Python toolchain in the frontend job.
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");
const backendDir = resolve(repoRoot, "backend");
const outFile = resolve(__dirname, "..", "lib", "api.gen.ts");

// 1. Dump the OpenAPI schema to a buffer via `uv run --project backend python -c …`.
const dumpScript = [
  "from notebookai.api.app import create_app",
  "import json, sys",
  "sys.stdout.write(json.dumps(create_app().openapi()))",
].join("; ");

console.log("[gen-api] dumping OpenAPI schema from FastAPI app …");
const dumpResult = spawnSync(
  "uv",
  ["run", "--project", backendDir, "python", "-c", dumpScript],
  { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] },
);
if (dumpResult.status !== 0) {
  console.error("[gen-api] python dump failed");
  process.exit(dumpResult.status ?? 1);
}
const openapiJson = dumpResult.stdout;

// 2. Write the schema to a temp file (openapi-typescript 7.x dropped stdin)
//    and run the local CLI against it. Local invocation keeps the generator
//    version pinned via the lockfile rather than picking up @latest.
const tmp = mkdtempSync(join(tmpdir(), "notebookai-openapi-"));
const schemaFile = join(tmp, "openapi.json");
writeFileSync(schemaFile, openapiJson, "utf8");

console.log("[gen-api] running openapi-typescript …");
const cli = resolve(__dirname, "..", "node_modules", ".bin", "openapi-typescript");
const genResult = spawnSync(cli, [schemaFile], {
  encoding: "utf8",
  stdio: ["ignore", "pipe", "inherit"],
});
rmSync(tmp, { recursive: true, force: true });
if (genResult.status !== 0) {
  console.error("[gen-api] openapi-typescript failed");
  process.exit(genResult.status ?? 1);
}

// 3. Write the result with a banner so the file is obviously generated.
const banner =
  "/* eslint-disable */\n" +
  "/**\n" +
  " * AUTO-GENERATED by `pnpm gen:api`. Do not edit by hand — regenerate\n" +
  " * after backend schema changes. Source: FastAPI app.openapi().\n" +
  " */\n";

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + genResult.stdout, "utf8");
console.log(`[gen-api] wrote ${outFile}`);
