/* eslint-disable */
/**
 * AUTO-GENERATED by `pnpm gen:api`. Do not edit by hand — regenerate
 * after backend schema changes. Source: FastAPI app.openapi().
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_api_notebooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_notebooks__notebook_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_notebooks__notebook_id__delete"];
        options?: never;
        head?: never;
        /** Patch */
        patch: operations["patch_api_notebooks__notebook_id__patch"];
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Library */
        get: operations["list_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Demo
         * @description Scaffold the demo notebook (or return it if it already exists).
         *
         *     Idempotent: a second call returns the same notebook without
         *     erroring or rewriting the on-disk content.
         */
        post: operations["create_demo_api_library_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register External */
        post: operations["register_external_api_library_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/external/{encoded_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deregister External */
        delete: operations["deregister_external_api_library_external__encoded_path__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Source */
        post: operations["ingest_source_api_notebooks__notebook_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/ingest/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest File */
        post: operations["ingest_file_api_notebooks__notebook_id__ingest_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_notebooks__notebook_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats_api_notebooks__notebook_id__chats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/chats/{chat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat */
        get: operations["get_chat_api_notebooks__notebook_id__chats__chat_id__get"];
        put?: never;
        post?: never;
        /** Delete Chat */
        delete: operations["delete_chat_api_notebooks__notebook_id__chats__chat_id__delete"];
        options?: never;
        head?: never;
        /** Patch Chat */
        patch: operations["patch_chat_api_notebooks__notebook_id__chats__chat_id__patch"];
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/lint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Lint */
        post: operations["trigger_lint_api_notebooks__notebook_id__lint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/lint/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_api_notebooks__notebook_id__lint_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/lint/findings/{finding_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Finding */
        post: operations["resolve_finding_api_notebooks__notebook_id__lint_findings__finding_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/lint/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Budget */
        get: operations["read_budget_api_notebooks__notebook_id__lint_budget_get"];
        put?: never;
        /** Update Budget */
        post: operations["update_budget_api_notebooks__notebook_id__lint_budget_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/lint/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Schedule */
        get: operations["read_schedule_api_notebooks__notebook_id__lint_schedule_get"];
        put?: never;
        /** Update Schedule */
        post: operations["update_schedule_api_notebooks__notebook_id__lint_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/lint/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Now */
        post: operations["run_now_api_notebooks__notebook_id__lint_run_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_notebooks__notebook_id__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/articles/{path}/backlinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Article Backlinks */
        get: operations["article_backlinks_api_notebooks__notebook_id__articles__path__backlinks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/articles/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Article */
        get: operations["read_article_api_notebooks__notebook_id__articles__path__get"];
        /** Write Article */
        put: operations["write_article_api_notebooks__notebook_id__articles__path__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log */
        get: operations["get_log_api_notebooks__notebook_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_api_notebooks__notebook_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/history/{sha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Entry */
        get: operations["get_history_entry_api_notebooks__notebook_id__history__sha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/history/{sha}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert History Entry */
        post: operations["revert_history_entry_api_notebooks__notebook_id__history__sha__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notebooks/{notebook_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_notebooks__notebook_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentConfig
         * @description `notebook.json.agent` sub-object.
         */
        AgentConfig: {
            /**
             * Model
             * @default claude-sonnet-4-6
             */
            model: string;
            /**
             * Lint Model
             * @default claude-haiku-4-5-20251001
             */
            lint_model: string;
            /**
             * Lint Schedule
             * @default hourly
             * @enum {string}
             */
            lint_schedule: "hourly" | "daily" | "off";
            /**
             * Lint Budget Tokens Per Day
             * @default 50000
             */
            lint_budget_tokens_per_day: number;
            /**
             * Lint Schedule Enabled
             * @default true
             */
            lint_schedule_enabled: boolean;
            /**
             * Lint Schedule Interval Minutes
             * @default 60
             */
            lint_schedule_interval_minutes: number;
        } & {
            [key: string]: unknown;
        };
        /** AgentStatus */
        AgentStatus: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ArticleContent */
        ArticleContent: {
            /** Path */
            path: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** ArticleSummary */
        ArticleSummary: {
            /** Path */
            path: string;
            /** Title */
            title: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Prompt */
            prompt: string;
            /**
             * Archive
             * @default false
             */
            archive: boolean;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** Chat Id */
            chat_id?: string | null;
        };
        /** BacklinksResponse */
        BacklinksResponse: {
            /** Path */
            path: string;
            /** Backlinks */
            backlinks: string[];
        };
        /** Body_ingest_file_api_notebooks__notebook_id__ingest_file_post */
        Body_ingest_file_api_notebooks__notebook_id__ingest_file_post: {
            /** File */
            file: string;
            /** Topic Hint */
            topic_hint?: string | null;
        };
        /** BudgetOut */
        BudgetOut: {
            /** Notebook Id */
            notebook_id: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Input Tokens Used */
            input_tokens_used: number;
            /** Output Tokens Used */
            output_tokens_used: number;
            /** Input Limit */
            input_limit: number;
            /** Output Limit */
            output_limit: number;
            /** Last Op At */
            last_op_at?: string | null;
            /** Denied Op Count */
            denied_op_count: number;
        };
        /** BudgetUpdate */
        BudgetUpdate: {
            /** Input Limit */
            input_limit?: number | null;
            /** Output Limit */
            output_limit?: number | null;
        };
        /** ChatPatch */
        ChatPatch: {
            /** Title */
            title: string;
        };
        /** CreateNotebookRequest */
        CreateNotebookRequest: {
            /** Name */
            name: string;
            /**
             * Git Enabled
             * @default true
             */
            git_enabled: boolean;
            /** Description */
            description?: string | null;
        };
        /** DemoResponse */
        DemoResponse: {
            notebook: components["schemas"]["NotebookEntry"];
        };
        /**
         * EmbeddingsConfig
         * @description `notebook.json.embeddings` sub-object.
         */
        EmbeddingsConfig: {
            /**
             * Model
             * @default bge-small-en-v1.5
             */
            model: string;
            /**
             * Dim
             * @default 384
             */
            dim: number;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryDetail */
        HistoryDetail: {
            /** Sha */
            sha: string;
            /** Author */
            author?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Subject */
            subject: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Op */
            op?: string | null;
            /** Op Id */
            op_id?: string | null;
            /**
             * Files Changed
             * @default []
             */
            files_changed: string[];
            /**
             * Insertions
             * @default 0
             */
            insertions: number;
            /**
             * Deletions
             * @default 0
             */
            deletions: number;
            /**
             * Diff
             * @default
             */
            diff: string;
        };
        /** HistoryEntry */
        HistoryEntry: {
            /** Sha */
            sha: string;
            /** Author */
            author?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Subject */
            subject: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Op */
            op?: string | null;
            /** Op Id */
            op_id?: string | null;
            /**
             * Files Changed
             * @default []
             */
            files_changed: string[];
            /**
             * Insertions
             * @default 0
             */
            insertions: number;
            /**
             * Deletions
             * @default 0
             */
            deletions: number;
        };
        /** IngestAccepted */
        IngestAccepted: {
            /** Op Id */
            op_id: string;
            /** Notebook Id */
            notebook_id: string;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Source */
            source: string;
            /** Source Type */
            source_type?: ("url" | "pdf" | "youtube") | null;
            /** Topic Hint */
            topic_hint?: string | null;
        };
        /** LintAccepted */
        LintAccepted: {
            /** Op Id */
            op_id: string;
            /** Notebook Id */
            notebook_id: string;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
        };
        /** LintFindingOut */
        LintFindingOut: {
            /** Id */
            id: string;
            /** Notebook Id */
            notebook_id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** LintRequest */
        LintRequest: {
            /**
             * Mode
             * @default light
             * @enum {string}
             */
            mode: "light" | "full";
        };
        /** LogEntry */
        LogEntry: {
            /** Op */
            op?: string | null;
            /** Summary */
            summary: string;
            /** Source */
            source: string;
            /** Sha */
            sha?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * NotebookEntry
         * @description One entry in the library listing.
         *
         *     The shape is what the API surfaces to the frontend; see ``CONTRACTS.md``
         *     § Decisions row 4.
         */
        NotebookEntry: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Created At */
            created_at?: string | null;
            /** Last Op At */
            last_op_at?: string | null;
            /**
             * Article Count
             * @default 0
             */
            article_count: number;
            /**
             * Chat Count
             * @default 0
             */
            chat_count: number;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /**
             * Git Enabled
             * @default false
             */
            git_enabled: boolean;
        };
        /**
         * NotebookMeta
         * @description Canonical `.notebookai/notebook.json` schema.
         */
        NotebookMeta: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Git Enabled
             * @default true
             */
            git_enabled: boolean;
            agent?: components["schemas"]["AgentConfig"];
            embeddings?: components["schemas"]["EmbeddingsConfig"];
            /** Description */
            description?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * NotebookMetaWithStatus
         * @description `NotebookMeta` plus a runtime ``agent_status`` field for the UI.
         */
        NotebookMetaWithStatus: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Git Enabled
             * @default true
             */
            git_enabled: boolean;
            agent?: components["schemas"]["AgentConfig"];
            embeddings?: components["schemas"]["EmbeddingsConfig"];
            /** Description */
            description?: string | null;
            /**
             * @default {
             *       "available": false
             *     }
             */
            agent_status: components["schemas"]["AgentStatus"];
        } & {
            [key: string]: unknown;
        };
        /** PatchNotebookRequest */
        PatchNotebookRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Path */
            path: string;
        };
        /** ResolveBody */
        ResolveBody: {
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "reject";
        };
        /** ScheduleUpdate */
        ScheduleUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Interval Minutes */
            interval_minutes?: number | null;
        };
        /**
         * SchedulerStatus
         * @description Snapshot returned to the API surface.
         */
        SchedulerStatus: {
            /** Notebook Id */
            notebook_id: string;
            /** Enabled */
            enabled: boolean;
            /** Interval Minutes */
            interval_minutes: number;
            /** Last Run At */
            last_run_at?: number | null;
            /** Next Run At */
            next_run_at?: number | null;
            /** Last Result */
            last_result?: ("ran" | "skipped" | "error") | null;
            /** Last Skip Reason */
            last_skip_reason?: string | null;
            /** Last Finding Count */
            last_finding_count?: number | null;
            /**
             * Idle
             * @default false
             */
            idle: boolean;
            /**
             * Running
             * @default false
             */
            running: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WriteArticleRequest */
        WriteArticleRequest: {
            /** Content */
            content: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_api_notebooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotebookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_notebooks__notebook_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookMetaWithStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_notebooks__notebook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_api_notebooks__notebook_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchNotebookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookEntry"][];
                };
            };
        };
    };
    create_demo_api_library_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoResponse"];
                };
            };
        };
    };
    register_external_api_library_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotebookEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deregister_external_api_library_external__encoded_path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encoded_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_source_api_notebooks__notebook_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_file_api_notebooks__notebook_id__ingest_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_file_api_notebooks__notebook_id__ingest_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_notebooks__notebook_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chats_api_notebooks__notebook_id__chats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_api_notebooks__notebook_id__chats__chat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_api_notebooks__notebook_id__chats__chat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_chat_api_notebooks__notebook_id__chats__chat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                chat_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_lint_api_notebooks__notebook_id__lint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LintAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_notebooks__notebook_id__lint_findings_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LintFindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_finding_api_notebooks__notebook_id__lint_findings__finding_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LintFindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_budget_api_notebooks__notebook_id__lint_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_budget_api_notebooks__notebook_id__lint_budget_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_schedule_api_notebooks__notebook_id__lint_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_schedule_api_notebooks__notebook_id__lint_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_now_api_notebooks__notebook_id__lint_run_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_notebooks__notebook_id__articles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    article_backlinks_api_notebooks__notebook_id__articles__path__backlinks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklinksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_article_api_notebooks__notebook_id__articles__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_article_api_notebooks__notebook_id__articles__path__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteArticleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_api_notebooks__notebook_id__log_get: {
        parameters: {
            query?: {
                op?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_notebooks__notebook_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
                since_sha?: string | null;
                op?: string | null;
            };
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_entry_api_notebooks__notebook_id__history__sha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
                sha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_history_entry_api_notebooks__notebook_id__history__sha__revert_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Confirm"?: string | null;
            };
            path: {
                notebook_id: string;
                sha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_notebooks__notebook_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notebook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
